name: Build Android Bundle (.aab)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install dependencies & Build
        run: |
          npm install
          npm run build
          npx cap add android
          npx cap copy

      - name: Build Android Bundle (.aab)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Upload .aab artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
